Lecture05課題提出
iasuka0901/RaiseTech_study pull request #5
Opened 2024-07-13 03:42 UTC by iasuka0901

## 第５回課題レビューをお願いします。

### 実施内容
#### lecture05.mdに実施内容と感想を記載しました。

1.組み込みサーバ(Puma)だけで動作確認<br>
2.組み込みサーバーとUnix Socketを使ったRailsアプリの動作確認<br>
3.Nginxの単体起動確認<br>
4.Webサーバー(Nginx)とAPサーバー(Puma)と役割をわけて動作<br>
5.ALBのインバウンド設定<br>
6.ALBのアウトバウンドの設定<br>
7.ヘルスステータスの確認（Healthyの確認）<br>
8.ALB経由でのアクセス<br>
9.S3バケットの作成<br>
10.IAMユーザの作成<br>
11.IAMロールの作成<br>
12.アプリで登録した画像をS3へ保存<br>
13.アプリでS3に保管した画像を表示<br>
14.AWS構成図<br>

2024-07-13 13:41 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-07-13 13:41 UTC, MasatoshiMizumoto commented on image/14.AWS構成図.png
IGWがモノクロテーマになっているので、カラー版でお願いします！！

2024-07-14 00:08 UTC, iasuka0901 commented on image/14.AWS構成図.png
@MasatoshiMizumoto 
確認ありがとうございます。
カラー版に修正しました。

2024-07-14 00:23 UTC, MasatoshiMizumoto approved these changes
LGTMです！！

2024-07-15 11:29 UTC, merged